version: "2"
services:
  postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=gliscor-simulation
