name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_ENV: ci
  CI: true
jobs:
  test-final-project:
    name: Test Final Project
    runs-on: ubuntu-latest
    container: node:16.13.2
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Go to Final Project Directory
        run: cd final-project
      - name: Install Dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
